// <auto-generated />
using System;
using Doodoo.Modules.Inventory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doodoo.Modules.Inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260716175305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Doodoo.Modules.Inventory.Entities.InventoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "DefinitionId")
                        .IsUnique();

                    b.ToTable("InventoryEntries", "inventory");
                });

            modelBuilder.Entity("Doodoo.Modules.Inventory.Entities.ItemDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Effect")
                        .HasColumnType("integer");

                    b.Property<int>("EffectAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<bool>("Stackable")
                        .HasColumnType("boolean");

                    b.Property<int?>("UnlockAtLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ItemDefinitions", "inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Animaties",
                            Content = "confetti",
                            ContentType = 2,
                            Description = "De standaard voltooiings-animatie.",
                            Effect = 0,
                            EffectAmount = 0,
                            IsActive = true,
                            IsDefault = true,
                            Key = "default-confetti",
                            Kind = 0,
                            Name = "Confetti",
                            Slot = 5,
                            Stackable = false
                        },
                        new
                        {
                            Id = 2,
                            Category = "Achtergrond",
                            Content = "default",
                            ContentType = 2,
                            Effect = 0,
                            EffectAmount = 0,
                            IsActive = true,
                            IsDefault = true,
                            Key = "default-app-background",
                            Kind = 0,
                            Name = "Standaard achtergrond",
                            Slot = 1,
                            Stackable = false
                        },
                        new
                        {
                            Id = 3,
                            Category = "Achtergrond",
                            Content = "{\"version\":1,\"slot\":\"AppBackground\",\"layers\":[{\"type\":\"gradient\",\"gradient\":{\"from\":\"#0f172a\",\"to\":\"#1e1b4b\",\"angle\":135},\"position\":\"cover\",\"zIndex\":0},{\"type\":\"image\",\"url\":\"https://assets.doo-doo.nl/backgrounds/stars.png\",\"position\":\"cover\",\"opacity\":0.6,\"zIndex\":1,\"animation\":{\"preset\":\"float\",\"durationMs\":8000}}]}",
                            ContentType = 1,
                            Description = "Een geanimeerde sterrenhemel-achtergrond.",
                            Effect = 0,
                            EffectAmount = 0,
                            IsActive = true,
                            IsDefault = false,
                            Key = "starry-night",
                            Kind = 0,
                            Name = "Sterrennacht",
                            Slot = 1,
                            Stackable = false
                        },
                        new
                        {
                            Id = 4,
                            Category = "Todo's",
                            Content = "default",
                            ContentType = 2,
                            Effect = 0,
                            EffectAmount = 0,
                            IsActive = true,
                            IsDefault = true,
                            Key = "default-todo-card",
                            Kind = 0,
                            Name = "Standaard todo-kaart",
                            Slot = 2,
                            Stackable = false
                        },
                        new
                        {
                            Id = 5,
                            Category = "Buttons",
                            Content = "default",
                            ContentType = 2,
                            Effect = 0,
                            EffectAmount = 0,
                            IsActive = true,
                            IsDefault = true,
                            Key = "default-nav-buttons",
                            Kind = 0,
                            Name = "Standaard knoppen",
                            Slot = 3,
                            Stackable = false
                        },
                        new
                        {
                            Id = 6,
                            Category = "Buttons",
                            Content = "{\"version\":1,\"slot\":\"NavButtons\",\"layers\":[],\"tokens\":{\"--nav-btn-bg\":\"#1e1b4b\",\"--nav-btn-fg\":\"#e0e7ff\",\"--nav-btn-radius\":\"16px\"}}",
                            ContentType = 1,
                            Description = "Herskin de navigatieknoppen (paars/neon).",
                            Effect = 0,
                            EffectAmount = 0,
                            IsActive = true,
                            IsDefault = false,
                            Key = "neon-nav-buttons",
                            Kind = 0,
                            Name = "Neon knoppen",
                            Slot = 3,
                            Stackable = false
                        },
                        new
                        {
                            Id = 7,
                            Category = "Profiel",
                            Content = "default",
                            ContentType = 2,
                            Effect = 0,
                            EffectAmount = 0,
                            IsActive = true,
                            IsDefault = true,
                            Key = "default-profile-button",
                            Kind = 0,
                            Name = "Standaard profielknop",
                            Slot = 4,
                            Stackable = false
                        },
                        new
                        {
                            Id = 8,
                            ContentType = 0,
                            Description = "Levert 20 goud op bij gebruik.",
                            Effect = 1,
                            EffectAmount = 20,
                            IsActive = true,
                            IsDefault = false,
                            Key = "bag-of-coins",
                            Kind = 1,
                            Name = "Zakje goud",
                            Slot = 0,
                            Stackable = true
                        },
                        new
                        {
                            Id = 9,
                            ContentType = 0,
                            Description = "Ontgrendelt pro-functies.",
                            Effect = 0,
                            EffectAmount = 0,
                            IsActive = true,
                            IsDefault = false,
                            Key = "pro-membership",
                            Kind = 2,
                            Name = "Pro membership",
                            Slot = 0,
                            Stackable = false
                        });
                });

            modelBuilder.Entity("Doodoo.Modules.Inventory.Entities.InventoryEntry", b =>
                {
                    b.HasOne("Doodoo.Modules.Inventory.Entities.ItemDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });
#pragma warning restore 612, 618
        }
    }
}
