// <auto-generated />
using System;
using Doodoo.Modules.Currency;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doodoo.Modules.Currency.Migrations
{
    [DbContext(typeof(CurrencyDbContext))]
    [Migration("20260703135431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("currency")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoodooApi.Models.Main.CurrencyAccounts.CurrencyAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Gold")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sapphires")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("CurrencyAccounts", "currency");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceIdGuid")
                        .HasColumnType("uuid");

                    b.Property<int?>("SourceIdInt")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyAccountId");

                    b.HasIndex("SourceType", "SourceIdGuid")
                        .IsUnique()
                        .HasFilter("\"SourceIdGuid\" IS NOT NULL");

                    b.HasIndex("SourceType", "SourceIdInt")
                        .IsUnique()
                        .HasFilter("\"SourceIdInt\" IS NOT NULL");

                    b.ToTable("Transactions", "currency");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Transactions.TransactionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionRecords", "currency");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Transactions.Transaction", b =>
                {
                    b.HasOne("DoodooApi.Models.Main.CurrencyAccounts.CurrencyAccount", "CurrencyAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyAccount");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Transactions.TransactionRecord", b =>
                {
                    b.HasOne("DoodooApi.Models.Main.Transactions.Transaction", "Transaction")
                        .WithMany("TransactionRecords")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.CurrencyAccounts.CurrencyAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Transactions.Transaction", b =>
                {
                    b.Navigation("TransactionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
