// <auto-generated />
using System;
using Doodoo.Modules.Todos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doodoo.Modules.Todos.Migrations
{
    [DbContext(typeof(TodosDbContext))]
    [Migration("20260707223000_AddScopedTodoOrdering")]
    partial class AddScopedTodoOrdering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("todos")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Doodoo.Modules.Todos.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DailyStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSaga")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemCategory")
                        .HasColumnType("integer");

                    b.Property<int>("ItemDifficulty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastCompletedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastWeeklyCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PreviousCompletedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WeeklyStreak")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "ItemCategory", "ParentId", "Order");

                    b.HasIndex("ParentId");

                    b.ToTable("TodoItems", "todos");
                });

            modelBuilder.Entity("Doodoo.Modules.Todos.Entities.TodoItem", b =>
                {
                    b.HasOne("Doodoo.Modules.Todos.Entities.TodoItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Doodoo.Modules.Todos.Entities.TodoItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
