// <auto-generated />
using System;
using Doodoo.Modules.Rewards;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doodoo.Modules.Rewards.Migrations
{
    [DbContext(typeof(RewardsDbContext))]
    [Migration("20260703135439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rewards")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoodooApi.Models.Main.Rewards.DifficultyRewardRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<decimal>("GoldAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("SapphireAmount")
                        .HasColumnType("integer");

                    b.Property<float>("SapphireChance")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("DifficultyRewardRules", "rewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 0,
                            GoldAmount = 0.4m,
                            SapphireAmount = 1,
                            SapphireChance = 0.01f
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = 1,
                            GoldAmount = 0.7m,
                            SapphireAmount = 1,
                            SapphireChance = 0.05f
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = 2,
                            GoldAmount = 1m,
                            SapphireAmount = 1,
                            SapphireChance = 0.1f
                        },
                        new
                        {
                            Id = 4,
                            Difficulty = 3,
                            GoldAmount = 1.3m,
                            SapphireAmount = 1,
                            SapphireChance = 0.15f
                        });
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Rewards.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Rewards", "rewards");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Rewards.RewardClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RewardId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("UserId");

                    b.ToTable("RewardClaims", "rewards");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Rewards.RewardCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer");

                    b.Property<int?>("RewardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.ToTable("RewardCosts", "rewards");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Rewards.RewardClaim", b =>
                {
                    b.HasOne("DoodooApi.Models.Main.Rewards.Reward", "Reward")
                        .WithMany("Claims")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Rewards.RewardCost", b =>
                {
                    b.HasOne("DoodooApi.Models.Main.Rewards.Reward", "Reward")
                        .WithMany("RewardCosts")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("DoodooApi.Models.Main.Rewards.Reward", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("RewardCosts");
                });
#pragma warning restore 612, 618
        }
    }
}
